version: '3'


tasks:
  build:
    desc: "Build a docker image"
    cmds:
      - docker build -t tg_redirect .
  run:
    desc: "Run a container in detach mode"
    cmds:
      - docker run -d -p 9999:8000 --name tg_redirect tg_redirect
  stop:
    desc: "Stop a container"
    cmds:
      - docker stop tg_redirect
  rm:
    desc: "Remove old container"
    cmds:
      - docker rm tg_redirect
